### ISSUE TITLE
SMTP notification is not working fpr port different from 25

### ISSUE THREAD

**Issue by SadE54** [esofthead/mycollab#4]
Hi,

It seems there's a problem with the SMTP configuration / notifications.
I want to use GMail as smtp server , so I have to use port 587 .
When configuring the SMTP server , the connection was OK.
But when sending a notificatin it fails....
Looking at the logs, it seems mycollab always want to use port 25 whatever is defined in setting file.

17:39:00,061 ERROR ErrorLogger:2425 - Job (DEFAULT.sendErrorReportEmailJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: com.esofthead.mycollab.core.MyCollabException: org.apache.commons.mail.EmailException: Sending the email to the following server failed : localhost:25]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.esofthead.mycollab.core.MyCollabException: org.apache.commons.mail.EmailException: Sending the email to the following server failed : localhost:25
	at com.esofthead.mycollab.module.mail.DefaultMailer.sendHTMLMail(DefaultMailer.java:129)
	at com.esofthead.mycollab.module.mail.DefaultMailer.sendHTMLMail(DefaultMailer.java:140)
	at com.esofthead.mycollab.schedule.jobs.SendingErrorReportEmailJob.executeInternal(SendingErrorReportEmailJob.scala:49)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : localhost:25
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410)
	at org.apache.commons.mail.Email.send(Email.java:1437)
	at com.esofthead.mycollab.module.mail.DefaultMailer.sendHTMLMail(DefaultMailer.java:127)
	... 5 more
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;
  nested exception is:
	java.net.SocketException: Network is unreachable: connect
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1972)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:642)
	at javax.mail.Service.connect(Service.java:317)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
	... 7 more
Caused by: java.net.SocketException: Network is unreachable: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:317)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:233)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1938)

**Comment by haiphucnguyen** [comment]
Thank you for your detail information. This issue is forwarded to the development team and we will back to you today. But could you give me the smtp host information in the mycollab.properties config file. Its key is mail.smtphost

This file is located at [sub project] mycollab-app-community/src/main/conf if you run in the IDE or %MyCOLLAB_HOME%/conf if you use MyCollab installer.

**Comment by SadE54** [comment]
here  the details ( As you see I replaced my real login/password infos :)

mail.smtphost=smtp.gmail.com
mail.port=587
mail.username=mylogin
mail.password=mypassword
mail.isTLS=true
mail.noreply=noreply@mycollab.com

2015-04-22 18:39 GMT-07:00 Nguyen Phuc Hai <notifications@github.com>:

**Comment by haiphucnguyen** [comment]
Uhm, it is the strange issue. Are you running MyCollab in the IDE? If so, could you please get the latest sources and run again. 

You can check the current SMTP setting by go to the setup page (as in the attachment) and confirm which the values of SMTP. For sure, you can edit the SMTP setting then save, MyCollab will recognize the new values.
![screenshot from 2015-04-23 15 38 02](https://cloud.githubusercontent.com/assets/3423575/7294191/0517ab4c-e9d5-11e4-8388-f1defdc4208c.png)

If you use the MyCollab installer, we will release the next version in the next 1-2 days. Please inform me the status of issue. Thank you.

**Comment by SadE54** [comment]
What do you mean by IDE ?
I installed MyCollab on my Windows computer using the installer, and use
the startup batch to launch it.
Then I'ms using Chrome as a client.

2015-04-23 2:28 GMT-07:00 Nguyen Phuc Hai <notifications@github.com>:

**Comment by SadE54** [comment]
It seems I have no more acces to setup page, maybe since I changed the
default admin email.
I can access to :
Profile
Billing
User &Roles
Logout

Setup line is not there :-/

2015-04-23 2:56 GMT-07:00 yann suisini <yannsuisini@gmail.com>:

**Comment by haiphucnguyen** [comment]
Never mind, I know where you install MyCollab  :). We will have the new release within the next 24-48 hours, and I would like to ask you upgrade to the higher version and confirm whether the issue is gone. We also provide a utility to let system admin can change the SMTP setting without restart.

If you download the MyCollab 5.0.4 or higher, you do not need go to the Sourceforge and download the latest version. When we release the new version, if you are the admin and access MyCollab then it will ask you upgrade and help you do the upgrade process automatically. Please stay tune for the new version.

**Comment by haiphucnguyen** [comment]
We have released the new version 5.0.5. If you install MyCollab from the version 5.0.4, then the upgrade process should be simple. It will ask you would you like auto upgrade, click 'yes' and it will do the rest for you.
![screenshot from 2015-04-25 16 50 16](https://cloud.githubusercontent.com/assets/3423575/7332477/4b2b2c16-eb6b-11e4-9356-acfc0ebbc3f6.png)

This is the strange issue when we do not use any default SMTP values such as localhost, and we can not reproduce issue on our side, so could you please upgrade MyCollab and confirm whether the issue still be happened. From 5.0.5, we allow admin can view and change the SMTP settings in the application and take it effectively right away. So you can verify whether MyCollab uses the right SMTP values and tell us. Thank you.

PS: We try to response any question within 1 business day but our office is closed for 3 days in the next week, and I will try to support your problem as soon as possible.

**Comment by SadE54** [comment]
Thanks for you answer . I will try the new version monday !
Another thing , I think a forum is missing . We cannot at this time
exchange about mycollab with other users :-/

Yann


2015-04-25 11:57 GMT+02:00 Nguyen Phuc Hai <notifications@github.com>:

**Comment by haiphucnguyen** [comment]
Thank you. We are implementing the new style of forum and I will clone your question there :). I am looking forward your result and please tell me the result, we will try to resolve as soon as possible. Have a nice weekend.

**Comment by SadE54** [comment]
Hello,

I tied to upgrade from 5.0.4 . It freezed .
So I made a 5.0.5 fresh install (deleting old database , creating a new
one, installing the 5.05 setup).
During the SMTP setup at install, mycollab told me the connection was OK.
So I tried to invite a colleague , and it seems there's always the mail
server connection problem .... and always 25 for the port indicated in logs.
I joined the log file, I hope it could help

Regards,

Yann

2015-04-25 6:58 GMT-07:00 Nguyen Phuc Hai <notifications@github.com>:

**Comment by haiphucnguyen** [comment]
Hi Yann,
    Could you download the latest file we uploaded again at https://sourceforge.net/projects/mycollab/files/MyCollab_5.0.5.1/. It seems there is one corner area we did not cover all in the community version in sending email. We did download the file, install and run MyCollab as the fresh one and it works. I hope it works at your PC as well. Thank you.

Best regards,
Hai Nguyen

**Comment by SadE54** [comment]
Hi,

It's woking now for smtp :)
I can test deeply now , I 'll go back to you in a few days to talk about my
thoughts ;)

Best Regards,
Yann

2015-04-29 11:07 GMT-07:00 Nguyen Phuc Hai <notifications@github.com>:

**Comment by haiphucnguyen** [comment]
Hi Yann,

Glad to know it is working :). If you have further suggestion or question, please ask it at https://www.mycollab.com/qa/?ap_page=ask. We will try to resolve them all very soon. We want to make MyCollab is the best project management tool, so any suggestion is welcome :)

Hai
